### ISSUE TITLE
Image records with missing images

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/image-service#27]
There are lots of images that have a broken images. E.g. http://images.ala.org.au/image/details/66140333 - in this case it appears the Flickr URL is no longer active and an error message has been cached as the image: http://images.ala.org.au/store/e/9/1/0/2d944025-4521-421b-92a5-ead7fb04019e/original

We need to identify all broken images and then remove them or fix them. Advanced search does not allow this (that I could find).

**Comment by davidbairdala** [comment]
Hi Nick,

Yeah, I remember this - the ingest url was actually a flickr page url, not the image itself. I believe this was a problem with the biocache load that has been fixed since. 

Although you cannot use the advanced search to find actual broken images, because the data that was actually downloaded is html and not an image the image meta data scraper would have defaulted the image type to 'image/jpeg', but it would not have been able to determine it's height or width. Which means you could craft a query that returns all images with a mime type of 'image/jpeg' and a height and/or width of zero. You'd need to include the mime type, otherwise it would include audio files, which also have 0 height and width.

<img width="1218" alt="screen shot 2016-05-30 at 12 31 22 pm" src="https://cloud.githubusercontent.com/assets/6147079/15638387/3f6e3060-2663-11e6-9cb1-9abf7630546e.png">

Cheers, David.

**Comment by djtfmartin** [comment]
Ive added a "missing images" report to the admin screen in image-service. This should satisfy the require to identify missing images. There are other issues open for clearing out deleted images / duplicates, so im closing this one.
