### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by JeGoi** [AtlasOfLivingAustralia/image-service#35]
Ex: https://bioatlas.se/images/image/details/250408
in the title

**Comment by djtfmartin** [comment]
The encoding issues are fixed in the latest release. Here a screenshot from the old:

<img width="1327" alt="Screen Shot 2019-09-18 at 2 11 05 pm" src="https://user-images.githubusercontent.com/444897/65151582-469bcb00-da1e-11e9-8f5e-5b1d6ac14a59.png">

and the same data loaded into dev environment with new

<img width="1552" alt="Screen Shot 2019-09-18 at 2 10 36 pm" src="https://user-images.githubusercontent.com/444897/65151611-561b1400-da1e-11e9-9b12-c96cc68e20e9.png">
