### ISSUE TITLE
regression - /ws/findImagesByMetadata is missing imageId

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/image-service#95]
The response for /ws/findImagesByMetadata  is missing an `imageId` field which is used by specimens.ala.org.au and is currently causing the application to fail to render the images. This field should be added back into the response to remedy the problem.

**Comment by ansell** [comment]
Not sure how to test whether these changes fix the specimens issue outside of production currently because there is no `images-test.ala.org.au`+`biocache-ws-test.ala.org.au` system that contains the same images as production for a given collection. Linking `specimens-test.ala.org.au` to `images-dev.ala.org.au` doesn't work to select collections that we know exist because the images are referenced from `biocache-ws-test.ala.org.au` which, due to budget reasons, references production `images.ala.org.au` imageId's rather than any of the imageId's on `images-dev.ala.org.au`

**Comment by nickdos** [comment]
@djtfmartin how hard is it to move one of the set of images for a collection (first one in specimens.ala.org.au) over from prod image-service to `images-test`?

**Comment by ansell** [comment]
@nickdos We don't have an `images-test.ala.org.au` at this point. We have a low capacity `images-dev.ala.org.au` at the moment for testing image-service changes.
